version: "3"

volumes:
  redis:

services:
  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./:/app